spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/impetus
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true